"""Generate fastrich/_emoji_table.py from Rich's emoji shortcode table.

This fetches Rich's `_emoji_codes.py` at a pinned tag and emits the mapping
verbatim (names + glyphs) as an ASCII-escaped module, mirroring the width-table generator.

Source: https://github.com/Textualize/rich (MIT License).

Usage:
    python scripts/gen_emoji_table.py [--version 15.0.0] [--out PATH]
"""

import argparse
import ast
import urllib.request
from pathlib import Path

PINNED_VERSION = "15.0.0"
SOURCE_URL = (
    "https://raw.githubusercontent.com/Textualize/rich/v{version}/rich/_emoji_codes.py"
)


def _fetch(version) -> str:
    """Fetch Rich's _emoji_codes.py source at the given tag.

    Args:
        version: The Rich release version (without the leading 'v').

    Returns:
        The decoded source text.
    """
    url = SOURCE_URL.format(version=version)
    with urllib.request.urlopen(url) as resp:
        return resp.read().decode("utf-8")


def _extract_emoji(source) -> dict[str, str]:
    """Parse the EMOJI mapping out of the source via ast (no code execution).

    Args:
        source: The _emoji_codes.py source text.

    Returns:
        The shortcode -> glyph mapping.
    """
    tree = ast.parse(source)
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "EMOJI":
                    return ast.literal_eval(node.value)

    raise SystemExit("EMOJI mapping not found in source")


def render_module(version, emoji) -> str:
    """Render the _emoji_table.py module text.

    Args:
        version: The pinned Rich version.
        emoji: The shortcode -> glyph mapping.

    Returns:
        The module source, ASCII-only, sorted by shortcode for stable diffs.
    """
    lines = [
        '"""Generated shortcode -> emoji glyph table. DO NOT EDIT BY HAND.',
        "",
        f"Generated by scripts/gen_emoji_table.py from Rich v{version}",
        "(https://github.com/Textualize/rich, MIT License). Re-run that script to",
        "regenerate; do not edit this file directly.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f'EMOJI_VERSION = "rich-{version}"',
        "",
        "EMOJI: dict[str, str] = {",
    ]
    for name in sorted(emoji):
        lines.append(f"    {name!r}: {emoji[name]!a},")

    lines.append("}")

    return "\n".join(lines) + "\n"


def main() -> None:
    """Fetch, parse, and write the emoji table module."""
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default=PINNED_VERSION)
    ap.add_argument("--out", default="src/fastrich/_emoji_table.py")
    args = ap.parse_args()

    emoji = _extract_emoji(_fetch(args.version))
    Path(args.out).write_text(render_module(args.version, emoji), encoding="utf-8")
    print(f"wrote {len(emoji)} shortcodes to {args.out} (rich-{args.version})")


if __name__ == "__main__":
    main()
